version: '3.4'
services:
  flask_app:
    container_name: flask_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    networks:
      flask_network:
        aliases:
          - flask-network
  nginx:
    image: nginx
    container_name: flask_nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - flask_app
    networks:
      - flask_network
volumes:
  flask_volume:
networks:
  flask_network:
