---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: flask-app
data:
  mysql-db-name: db
  mysql-db-user: user
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: flask-app
data:
  mysql-password: N09rd05VTWZ3WW5TWnYK
  mysql-root-password: UkIwblFVeFlVZWhWT0gK
